# Generated by Django 2.0.3 on 2018-04-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='idioma',
            field=models.CharField(choices=[('EN', 'Ingles'), ('ES', 'Espanol'), ('FR', 'Frances'), ('PR', 'Portugues')], default='ES', max_length=20),
        ),
    ]
