# Generated by Django 2.0.3 on 2018-04-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0002_norma_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='pretag',
            field=models.CharField(choices=[['SVO', 'Subject Verb Object'], ['AHO', 'A-HOFELD']], default='SVO', max_length=100),
        ),
    ]
