# Generated by Django 2.0.3 on 2018-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0003_norma_pretag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='etiqueta_text',
            field=models.TextField(),
        ),
    ]
