# Generated by Django 2.0.3 on 2018-04-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0004_auto_20180427_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
    ]
