# Generated by Django 2.0.3 on 2018-04-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0005_auto_20180427_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='texto_etiquetado',
            field=models.TextField(default=''),
        ),
    ]
