# Generated by Django 2.0.3 on 2018-04-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normas', '0006_norma_texto_etiquetado'),
    ]

    operations = [
        migrations.AddField(
            model_name='norma',
            name='aprobacion_etiquetado',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddField(
            model_name='norma',
            name='observaciones_etiquetado',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
